// build-site.js — Assembles the deployable site/ directory for GitHub Pages
// and generates js/version.js from package.json (single version source).
// Run: node scripts/build-site.js
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const site = path.join(root, 'site');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

const COPY_PATHS = ['index.html', 'manifest.json', 'sw.js', 'css', 'js', 'icons'];
const COPY_IF_EXISTS = ['silent.html']; // added in Phase 2 (silent re-auth target)

function copy(src, dest) {
  const stat = fs.statSync(src);
  if (stat.isDirectory()) {
    fs.mkdirSync(dest, { recursive: true });
    for (const entry of fs.readdirSync(src)) {
      copy(path.join(src, entry), path.join(dest, entry));
    }
  } else {
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(src, dest);
  }
}

// Clean rebuild — no stale files, no node_modules/installers ever
fs.rmSync(site, { recursive: true, force: true });
fs.mkdirSync(site, { recursive: true });

for (const p of COPY_PATHS) copy(path.join(root, p), path.join(site, p));
for (const p of COPY_IF_EXISTS) {
  const src = path.join(root, p);
  if (fs.existsSync(src)) copy(src, path.join(site, p));
}

// Version single-sourcing: package.json is the source of truth.
// Global assignment for now — flips to an ESM export in Phase 2.
fs.writeFileSync(
  path.join(site, 'js', 'version.js'),
  `// Generated by scripts/build-site.js — do not edit\nwindow.APP_VERSION = '${pkg.version}';\n`
);

console.log(`site/ assembled (v${pkg.version})`);
